### ISSUE TITLE
Missing Scala 1.X versions artifacts

### ISSUE THREAD

**Issue by pfcoperez** [swagger-akka-http/swagger-pekko-http#3]
It seems only 2.X versions artifacts are published in Sonatype. I am testing the waters for a huge codebase migration from Akka to Pekko and we are using `swagger-akka-http` for Scala 2.13 on version `1.1.1`.

It would facilitate things a great deal to have this version available to use :pray: 

Thank you in advance!

**Comment by pjfanning** [comment]
That's a really old version with many versions published since - even in 1.x.y release range.

I don't want to go back through all the legacy versions of swagger-akka-http and produce Pekko versions.

I think it would be much simpler if you just copy the classes you need from swagger-akka-http and migrate them to Pekko yourself. Migrating to Pekko is pretty easy. See https://pekko.apache.org/docs/pekko/1.0.0/project/migration-guides.html

You can just embed a couple of these classes in your own project.

You can find the swagger-akka-http source at the v1.1.1 tag
https://github.com/swagger-akka-http/swagger-akka-http/tree/v1.1.1

**Comment by pfcoperez** [comment]
> I don't want to go back through all the legacy versions of swagger-akka-http and produce Pekko versions.

Makes perfect sense, you already have a large codebase at hand for that to be feasible.

> I think it would be much simpler if you just copy the classes you need from swagger-akka-http and migrate them to Pekko yourself. Migrating to Pekko is pretty easy. See https://pekko.apache.org/docs/pekko/1.0.0/project/migration-guides.html

I am migrating a big codebase to Pekko myself thanks to `find` and `sed`, just a few extra casses is not that bad :slightly_smiling_face: 

> You can just embed a couple of these classes in your own project.
> 
> You can find the swagger-akka-http source at the v1.1.1 tag https://github.com/swagger-akka-http/swagger-akka-http/tree/v1.1.1

Thank you!

**Comment by pjfanning** [comment]
Give me a shout if you run into trouble. If sed is not working out for you, it might be worth looking at https://github.com/jtjeferreira/pekko-scalafix
